[package]
name = "da-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "da"
path = "src/main.rs"

[dependencies]
da-domain = { workspace = true }
da-ports = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
da-adapters = { workspace = true }
da-application = { workspace = true }
da-graph = { workspace = true }
tracing-subscriber = { workspace = true }
chrono = { workspace = true }

[dev-dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
