#!/usr/bin/env python3
"""Generate the codebase-memory governance digest from canonical GSD artifacts.

The generated `.codebase-memory/adr.md` is intentionally a mirror, not the source
of truth. Canonical requirement and decision lifecycle stays in `.gsd/`.
"""

from __future__ import annotations

import argparse
import re
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / ".codebase-memory" / "adr.md"
REQUIREMENTS_PATH = ROOT / ".gsd" / "REQUIREMENTS.md"
DECISIONS_PATH = ROOT / ".gsd" / "DECISIONS.md"
ADR_DIR = ROOT / "doc" / "adr" / "m034"

SECRET_PATTERNS = (
    re.compile(r"sk-[A-Za-z0-9_-]{12,}"),
    re.compile(r"(?i)(api[_-]?key|secret|token|credential)\s*[:=]\s*[^\s`|]+"),
    re.compile(r"(?i)-----BEGIN [A-Z ]*PRIVATE KEY-----"),
)
FORBIDDEN_PAYLOAD_TERMS = (
    "raw_corpus_text",
    "raw_prompt",
    "full_text",
    "source_text",
    "embedding_vector",
)


@dataclass(frozen=True)
class RequirementEntry:
    req_id: str
    title: str
    status: str
    source: str
    owner: str


@dataclass(frozen=True)
class DecisionEntry:
    decision_id: str
    when: str
    scope: str
    decision: str
    choice: str


@dataclass(frozen=True)
class AdrEntry:
    adr_id: str
    title: str
    status: str
    path: str


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def clean_cell(value: str) -> str:
    value = value.strip()
    value = re.sub(r"\s+", " ", value)
    return value.replace("`", "'")


def check_safe_text(text: str) -> None:
    for pattern in SECRET_PATTERNS:
        if pattern.search(text):
            raise ValueError("governance digest contains secret-shaped content")
    lowered = text.lower()
    for term in FORBIDDEN_PAYLOAD_TERMS:
        if term in lowered:
            raise ValueError(f"governance digest contains forbidden payload term: {term}")


def parse_requirements(text: str) -> list[RequirementEntry]:
    entries: list[RequirementEntry] = []
    blocks = re.split(r"(?=^### R\d{3}\s+[—-]\s+)", text, flags=re.MULTILINE)
    for block in blocks:
        header = re.match(r"^### (R\d{3})\s+[—-]\s+(.+)$", block.strip(), flags=re.MULTILINE)
        if not header:
            continue
        req_id, title = header.group(1), clean_cell(header.group(2))
        status = extract_bullet(block, "Status") or "unknown"
        source = extract_bullet(block, "Source") or "unknown"
        owner = extract_bullet(block, "Primary owning slice") or "unassigned"
        entries.append(RequirementEntry(req_id, title, clean_cell(status), clean_cell(source), clean_cell(owner)))
    return entries


def parse_decisions(text: str) -> list[DecisionEntry]:
    entries: list[DecisionEntry] = []
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line.startswith("| D"):
            continue
        cells = [clean_cell(cell) for cell in line.strip("|").split("|")]
        if len(cells) < 8:
            continue
        entries.append(
            DecisionEntry(
                decision_id=cells[0],
                when=cells[1],
                scope=cells[2],
                decision=cells[3],
                choice=cells[4],
            )
        )
    return entries


def parse_adrs(adr_dir: Path) -> list[AdrEntry]:
    entries: list[AdrEntry] = []
    for path in sorted(adr_dir.glob("ADR-*.md")):
        text = read_text(path)
        header = re.search(r"^#\s+(ADR-\d+):\s+(.+)$", text, flags=re.MULTILINE)
        if not header:
            continue
        status = "unknown"
        status_match = re.search(r"^\*\*Status:\*\*\s*(.+?)\s*$", text, flags=re.MULTILINE)
        if status_match:
            status = clean_cell(status_match.group(1))
        entries.append(
            AdrEntry(
                adr_id=header.group(1),
                title=clean_cell(header.group(2)),
                status=status,
                path=str(path.relative_to(ROOT)),
            )
        )
    return entries


def extract_bullet(block: str, name: str) -> str | None:
    match = re.search(rf"^- {re.escape(name)}:\s*(.+)$", block, flags=re.MULTILINE)
    return match.group(1).strip() if match else None


def render_digest(
    requirements: list[RequirementEntry], decisions: list[DecisionEntry], adrs: list[AdrEntry]
) -> str:
    lines: list[str] = [
        "# daily-archive Governance Memory Mirror",
        "",
        "> Generated by `scripts/sync_codebase_memory_governance.py`.",
        "> GSD remains canonical for requirements and decisions; documented ADR files remain canonical for architecture decisions; GitNexus remains mandatory for code-impact safety.",
        "> This file is a compact codebase-memory recall mirror only. If it conflicts with `.gsd/` or `doc/adr/`, treat this file as stale and regenerate it.",
        "",
        "## Hybrid Governance Roles",
        "",
        "| Layer | Role | Canonical? |",
        "|---|---|---:|",
        "| GSD `.gsd/REQUIREMENTS.md` and `.gsd/DECISIONS.md` | Requirement and decision lifecycle | yes |",
        "| ADR docs under `doc/adr/` | Architecture decision rationale and binding notes | yes |",
        "| GitNexus | Pre-edit impact analysis and pre-commit change scope | yes for code safety workflow |",
        "| codebase-memory MCP | Fast semantic ADR/R/D recall mirror | no |",
        "",
        "## Requirement Index",
        "",
        "| ID | Status | Owner | Source | Title |",
        "|---|---|---|---|---|",
    ]
    for req in requirements:
        lines.append(f"| {req.req_id} | {req.status} | {req.owner} | {req.source} | {req.title} |")

    lines.extend([
        "",
        "## Decision Index",
        "",
        "| ID | When | Scope | Decision | Choice |",
        "|---|---|---|---|---|",
    ])
    for decision in decisions:
        lines.append(
            f"| {decision.decision_id} | {decision.when} | {decision.scope} | {decision.decision} | {decision.choice} |"
        )

    lines.extend([
        "",
        "## ADR Index",
        "",
        "| ADR | Status | Path | Title |",
        "|---|---|---|---|",
    ])
    for adr in adrs:
        lines.append(f"| {adr.adr_id} | {adr.status} | `{adr.path}` | {adr.title} |")

    lines.extend([
        "",
        "## ADR Relationship Graph Notes",
        "",
        "- ADR-000 establishes the Universal KB north-star scope and prevents overfitting to arXiv, PDFs, scientific papers, or RAG-only assumptions.",
        "- ADR-004 allows sidecars to produce candidate evidence, but not import-ready graph facts.",
        "- ADR-005 blocks direct extractor, parser, sidecar, adapter, or LLM-helper writes to GraphDB and requires candidate, validation, review, and readiness boundaries before any promotion.",
        "- M035 validates the no-write Universal KB prototype at fixture level.",
        "- M036 validates the no-write smoke on 5 real local article artifacts.",
        "- M037 consolidates the smoke control surface without changing ADR-005 or expanding beyond 5 articles.",
        "- D075 chooses the hybrid governance model: GSD canonical, GitNexus code-safety, codebase-memory fast recall mirror.",
        "- R062 requires this generated mirror to stay non-canonical and verifiable.",
        "",
        "## Refresh Commands",
        "",
        "```bash",
        "uv run python scripts/sync_codebase_memory_governance.py",
        "uv run python scripts/sync_codebase_memory_governance.py --check",
        "```",
        "",
    ])
    rendered = "\n".join(lines)
    check_safe_text(rendered)
    return rendered


def generate_digest() -> str:
    requirements = parse_requirements(read_text(REQUIREMENTS_PATH))
    decisions = parse_decisions(read_text(DECISIONS_PATH))
    adrs = parse_adrs(ADR_DIR)
    return render_digest(requirements, decisions, adrs)


def display_path(path: Path) -> str:
    try:
        return str(path.relative_to(ROOT))
    except ValueError:
        return str(path)


def write_digest(output: Path) -> None:
    digest = generate_digest()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(digest, encoding="utf-8")
    sys.stdout.write(f"wrote {display_path(output)}\n")


def check_digest(output: Path) -> None:
    expected = generate_digest()
    actual = read_text(output) if output.exists() else ""
    if actual != expected:
        raise SystemExit(f"{display_path(output)} is stale; run sync_codebase_memory_governance.py")
    sys.stdout.write(f"ok {display_path(output)}\n")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the generated digest is stale")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args(argv)

    output = args.output.resolve()
    if args.check:
        check_digest(output)
    else:
        write_digest(output)
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except ValueError as exc:
        sys.stderr.write(f"error: {exc}\n")
        raise SystemExit(1) from exc
